---
collections:
  - name: ansible.netcommon
  - name: ansible.utils
  - name: cisco.ios
  - name: community.general
 # Install a collection from Ansible Galaxy.
  - name: cisco.meraki
    source: https://galaxy.ansible.com