---

-
  hosts: infrastructure
 
  tasks: 
    - name: Capture SHOW VERSION
      cli_command:
        commands:  show version | i ersion
      register: version_output

    - name: Display OUTPUT
      debug:
        msg: Output is {{ version_output.stdout[0] }}

...