---

-
  hosts: infrastructure
 
  tasks: 
    - name: Capture SHOW VERSION
      cli_command:
        command:  show version | i ersion
      register: version_output
      when: ansible_net_system != "nxos"

    - name: Display OUTPUT
      debug:
        msg: Output is {{ version_output.stdout }}

...