---

-
  hosts: "{{ my_devices }}"
  gather_facts: "{{ my_facts }}"

  tasks:
    - name: Capture SHOW COMMAND
      cli_command:
        command:  "{{ my_cmd }}"
      register: cmd_output
      #when: ansible_net_system != "nxos"

    - name: Display OUTPUT
      debug:
        msg: Output is {{ cmd_output.stdout }}
      #when: ansible_net_system != "nxos"

...