---

-
  hosts: "{{ my_devices }}"
  gather_facts: "{{ my_facts }}"

  tasks:
    - name: Capture SHOW COMMAND
      cli_command:
        command:  "{{ my_cmd }}"
      register: cmd_output

    - name: Display OUTPUT, line by line
      debug:
        msg: Output is {{ cmd_output.stdout_lines }}

...