---
- name: Test hostvars access from credentials
  hosts: all
  gather_facts: true
  vars:
    my_test1: "{{ ec2_tag_Contact | default('It did NOT work', true) }}"

  tasks:
  # - name: Debug hostvars
  #   debug:
  #     var: hostvars

  # - name: Debug groups
  #   debug:
  #     var: groups

    - name: Print from tags
      debug:
        msg: "{{ ec2_tag_Contact }}"

    - name: Print from variables
      debug:
        msg: "{{ my_test1 }}"

    - name: Print from inventory
      debug:
        msg: "{{ my_test2 }}"

    - name: End message
      debug:
        msg: "All good, looks like debug: var: has an issue"
