---
- name: Install all security, critical, and rollup updates without a scheduled task
  hosts: all

  tasks:
  - name: Download and install Windows updates
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      reboot: yes