---

-
  hosts: "{{ my_devices }}"
  gather_facts: "{{ my_facts }}"

  tasks:
    - name: multi-line config
      cli_config:
        config: "{{ my_config }}"
        # config: |
        #   ipv4 access-list TEST_ACL
        #   permit 192.0.2.1
        #   remark doc-ip
