---
- name: NTP Server configuration compliance for Network Elements
  hosts: "{{ devices }}"
  connection: network_cli
  gather_facts: no
  vars:
    erase: false
    required_servers: []

  tasks:
    - name: Read inputs and prepare configs
      set_fact:
        required_servers: "{{ required_servers }} + [ 'ntp server {{ item }}' ]"
      with_items: "{{ ntp_servers }}"

    - name: Check existing NTP Servers
      include_role:
        name: ntpcheck
      when: ansible_network_os is defined

    # Adds ntp server entries in the ntp_servers variable if the variable erase is false
    - block:
      - name: Compare NTP servers and remove erroroneous entries
        cli_config:
          config: no {{ item }}
        loop: "{{ configured_servers }}"
        when:
          - configured_servers | length > 0
          - item not in required_servers

      - name: Ensure intended NTP servers are present
        cli_config:
          config: "{{ item }}"
        loop: "{{ required_servers }}"
      when: not erase|bool

    # Erases all ntp server entries if the variable erase is true
    - name: Remove all existing ntp server entries
      cli_config:
        config: no {{ item }}
      loop: "{{ configured_servers }}"
      when:
        - configured_servers | length > 0
        - erase|bool