---
- name: NTP Server configuration compliance for Network Elements
  hosts: "{{ devices }}"
  connection: network_cli
  gather_facts: no
  vars:
    erase: false
    required_servers: []
    in_servers: []
    out_servers: []
    missing: {}
    to_remove: {}

  tasks:
    - name: Read inputs and prepare configs
      set_fact:
        required_servers: "{{ required_servers }} + [ 'ntp server {{ item }}' ]"
      with_items: "{{ ntp_servers }}"

    - name: Check existing NTP Servers
      include_role:
        name: ntpcheck
      when: ansible_network_os is defined

    # Adds ntp server entries in the ntp_servers variable if the variable erase is false
    - block:
      - name: Compare NTP servers and remove erroroneous entries
        cli_config:
          config: no {{ item }}
        loop: "{{ configured_servers }}"
        when:
          - configured_servers | length > 0
          - item not in required_servers

      - name: Ensure intended NTP servers are present
        cli_config:
          config: "{{ item }}"
        loop: "{{ required_servers }}"
      when: not erase|bool

    # - name: Render template
    #   set_fact:
    #     rendered_template: "{{ lookup('template', 'report.j2') }}"

    - name: Save template to tempporary file
      template:
        src: report.j2
        dest: ./temp.html
        mode: '0755'
      when: missing | length > 0 or to_remove | length > 0
    
    # Creates and uploads a report to S3 
    - name: Upload report to S3
      aws_s3:
        bucket: mydemo.run
        src: "./temp.html"
        object: "index.html"
        mode: put
        metadata: 'Content-Type=text/html'
      when: missing | length > 0

    # Erases all ntp server entries if the variable erase is true
    - name: Remove all existing ntp server entries
      cli_config:
        config: no {{ item }}
      loop: "{{ configured_servers }}"
      when:
        - configured_servers | length > 0
        - erase|bool