---
# ansible-playbook --ask-vault-pass use-encrypted-file.yml

- name: Using data from an encrypted file
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  vars:
    the_key: "{{ lookup('file', '{{ playbook_dir }}/data.json') }}"

  tasks:
    - name: make sure we are running correct Ansible Version
      assert:
        that:
          - ansible_version.major >= 2
          - ansible_version.minor >= 9

    - name: Check the file exists
      stat:
        path: "{{ playbook_dir }}/data.json"
      register: stat_result
    - debug:
        var: stat_result
    - name: Complain if input fail doesn't exist
      fail:
        msg: "We need a file located at {{ playbook_dir }}/data.json"
      when:
        - not stat_result.stat.exists

    - name: Print output from file
      debug: msg="the content of the file is {{ lookup('file', '{{ playbook_dir }}/data.json') }}"

    - name: Print output from var
      debug: msg="the content of the file is {{ the_key }}"

    - name: Copy manually provided Key
      copy:
        content: "{{ the_key2 }}"
        dest: "{{ playbook_dir }}/private.pem"
        mode: '0400'
      vars:
        the_key2: "{{ lookup('file', '{{ playbook_dir }}/data.json') }}"
