---
# Need to add to requirements file these:
# ansible-galaxy collection install ansible.utils
# ansible-galaxy collection install ansible.netcommon
# ansible-galaxy collection install cisco.ios

- hosts: "{{ my_devices }}"
  connection: ansible.netcommon.network_cli
  gather_facts: "{{ my_facts }}"
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
  - name: Parse list of commands
    include_tasks: validate_commands.yml
    loop:
      - show version
      - show interfaces
      - show lldp neighbors
      - show ip bgp summary
      - show ip ospf neighbor
    loop_control:
      loop_var: command

  - name: Print all structured {{ command }} data - OPTION 1
    ansible.builtin.debug:
      var: my_dict

  - name: Print all structured {{ command }} data - OPTION 2
    ansible.builtin.debug:
      var: output.results[index] 
    loop:
      - 0
      - 1
      - 2
      - 3
      - 4
    loop_control:
      loop_var: index

...