- name: Fetch {{ command }} and parse it with pyATS
  ansible.utils.cli_parse:
    command: "{{ command }}"
    parser:
      name: ansible.netcommon.pyats
  register: output

- set_fact:
    my_dict: "{{ my_dict | default({}) | combine( {command: output['parsed']}) }}"

# - name: Print structured {{ command }} data
#   ansible.builtin.debug:
#     msg: "{{ my_dict[command] }}"