---
# Need to add to requirements file these:
# ansible-galaxy collection install ansible.utils
# ansible-galaxy collection install ansible.netcommon
# ansible-galaxy collection install cisco.ios

- hosts: "{{ my_devices }}"
  connection: ansible.netcommon.network_cli
  gather_facts: "{{ my_facts }}"
  vars:
    ansible_network_os: cisco.ios.ios

  tasks:
  - name: Fetch interface state and parse with pyats
    # ansible.utils.cli_parse:
    # temporary workaround: https://github.com/ansible-collections/ansible.utils/pull/45
    ansible.netcommon.cli_parse:
      command: show interface
      parser:
        name: ansible.netcommon.pyats
    register: ios_pyats_show_interface

  - name: print structured interface state data
    ansible.builtin.debug:
      msg: "{{ ios_pyats_show_interface['parsed'] }}"


...