- name: Fetch {{ command }} and parse it with pyATS
  ansible.utils.cli_parse:
    command: "{{ command }}"
    parser:
      name: ansible.netcommon.pyats
  register: output
  ignore_errors: true

- name: Add {{ command }} to dictionary with command outputs
  set_fact:
    my_dict: "{{ my_dict | default({}) | combine( { command: (output['parsed'] | default('empty', true)) }) }}"

# - name: Print structured {{ command }} data
#   ansible.builtin.debug:
#     msg: "{{ my_dict[command] }}"
