# This task will backup the configuration
- name: BACKUP THE CONFIG [{{ ansible_network_os | default("unknown OS")}}]
  ios_config:
    backup: yes
  register: config_output

# This task removes lines from the Current configuration... from the top of IOS routers show run
- name: REMOVE NON CONFIG LINES - LINE [{{ ansible_network_os | default("unknown OS")}}]
  lineinfile:
    path: "{{config_output.backup_path}}"
    line: "Building configuration..."
    state: absent
