- name: Get current NTP servers on IOS device
  cli_command:
    command: show run | i ntp server
  register: output

- name: Print current NTP servers on IOS device
  debug:
    var: output.stdout_lines
  when:
      - output.stdout | length > 0