- name: Get current NTP servers [IOS XR]
  cli_command:
    command: show run formal | i ntp server
  register: output

- name: Remove non config lines [IOS XR]
  set_fact:
    configured_servers: "{{ output.stdout_lines | difference(dummy_list) }}"
  vars:
    dummy_list:
      - "Building configuration..."

- name: Print current NTP servers [IOS XR]
  debug:
    var: configured_servers

## Generate report data
- name: Generate data for reporting
  include_tasks: 'report/data.yml'