- name: Get current NTP servers on IOS XR device
  cli_command:
    command: show run formal | i ntp server
  register: output

- name: DEBUG IOS XR stdout
  debug: 
    msg: "{{ output.stdout }}"

- name: Remove non config lines in IOS XR
  set_fact:
    servers: "{{ output.stdout_lines | difference(dummy_list) }}"
  vars:
    dummy_list:
      - "Building configuration..."

- name: Print current NTP servers on IOS XR device
  debug:
    var: servers
  when:
      - servers | length > 0


