- name: Get current NTP servers [IOS XR]
  cli_command:
    command: show run formal | i ntp server
  register: output

- name: Remove non config lines [IOS XR]
  set_fact:
    configured_servers: "{{ output.stdout_lines | difference(dummy_list) }}"
  vars:
    dummy_list:
      - "Building configuration..."

- name: Print current NTP servers [IOS XR]
  debug:
    var: configured_servers

- name: Determine configuration delta for reporting [IOS XR]
  set_fact:
    missing_servers: "{{ required_servers | difference(configured_servers) }}"
    unnecessary_servers: "{{ configured_servers | difference(required_servers) }}"

- name: Create list of NEW servers to configure [IOS XR]
  set_fact:
    in_servers: "{{ in_servers }} + [ '{{ item.split(' ')[-1] }}' ]"
  with_items: "{{ missing_servers }}"

- name: Create list of servers to remove [IOS XR]
  set_fact:
    out_servers: "{{ out_servers }} + [ '{{ item.split(' ')[-1] }}' ]"
  with_items: "{{ unnecessary_servers }}"

- name: Print out fidings for reporting [IOS XR]
  debug:
    msg:
    - "We are missing the following NTP Servers in IOS: {{ in_servers | list }}"
    - "We will delete these NTP Servers in IOS: {{ out_servers | list }}"
