- name: Get current NTP servers on IOS XR device
  cli_command:
    command: show run formal | i ntp server
  register: output

- name: Remove non config lines in IOS XR
  set_fact:
    configured_servers: "{{ output.stdout_lines | difference(dummy_list) }}"
  vars:
    dummy_list:
      - "Building configuration..."

- name: Print current NTP servers on IOS XR device
  debug:
    var: configured_servers

