- name: Get current NTP servers on IOS XR device
  cli_command:
    command: show run | i ntp server
  register: output

- name: DEBUG IOS XR stdout
  debug: 
    msg: "{{ output.stdout }}"

- name: Remove non config lines in IOS XR
  lineinfile:
    path: "{{ output.stdout[0] }}"
    #line: "Building configuration..."
    regexp: "Building configuration..."
    state: absent

- name: Print current NTP servers on IOS XR device
  debug:
    var: output.stdout_lines
  when:
      - output.stdout | length > 0


