- name: Get current ntp servers on device
  cli_command:
    command: show run | i ntp server
  register: output

- name: Remove non config lines
  lineinfile:
    path: "{{ output.stdout_lines[0] }}"
    line: "Building configuration..."
    state: absent
  when:
    - output|len gt 0

- name: Print current ntp servers
  debug:
    var: output.stdout_lines
  when:
    - output|len gt 0


