- name: Get current NTP servers [IOS XR]
  cli_command:
    command: show run formal | i ntp server
  register: output

- name: Remove non config lines [IOS XR]
  set_fact:
    configured_servers: "{{ output.stdout_lines | difference(dummy_list) }}"
  vars:
    dummy_list:
      - "Building configuration..."

- name: Print current NTP servers [IOS XR]
  debug:
    var: configured_servers

- name: Determine configuration delta for reporting [IOS XR]
  set_fact:
    missing_servers: "{{ required_servers | difference(configured_servers) | last }}"
    unnecessary_servers: "{{ configured_servers | difference(required_servers) | last }}"

- name: Print out fidings for reporting [IOS XR]
  debug:
    msg:
    - "We are missing the following NTP Servers in IOS XR: {{ missing_servers }}"
    - "We will delete this NTP Servers in IOS XR: {{ unnecessary_servers }}"
