- name: Get current NTP servers [NX-OS]
  ansible.netcommon.cli_command:
    command: show run | i 'ntp server'
  register: output

- name: Remove use-vrf default [NX-OS]
  ansible.builtin.set_fact:
    configured_servers: "{{ configured_servers }} + [ '{{ item | replace(' use-vrf default', '') }}' ]"
  with_items: "{{ output.stdout_lines }}"
  vars:
    configured_servers: []

- name: Print current NTP servers [NX-OS]
  ansible.builtin.debug:
    var: configured_servers

## Generate report data
- name: Generate data for reporting
  ansible.builtin.include_tasks: 'report/data.yml'
