- name: Get current NTP servers [NX-OS]
  cli_command:
    command: show run | i ntp server
  register: output

- name: Remove non config lines [NX-OS]
  set_fact:
    configured_servers: "{{ output.stdout_lines | difference(dummy_list) }}"
  vars:
    dummy_list:
      - "Building configuration..."

- name: Print current NTP servers [NX-OS]
  debug:
    var: configured_servers

## Generate report data
- name: Generate data for reporting
  include_tasks: 'report/data.yml'